config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "recipes#public"

  resources :recipes, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'generate_shopping_list', to: 'shopping_lists#generate'
  resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
  has_many :recipes, through: :recipe_food
  validates :price, :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
  has_many :food, through: :recipe_food

  validates :preparation_time, :cooking_time, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipe
  has_many :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @foods = current_user.food
  end

  def new
    @food = current_user.food.build
  end

  def create
    @food = current_user.food.build(food_params)

    if @food.save
      redirect_to foods_path, notice: 'Food Created!!'
    else
      @errors = @food.errors.full_messages
      flash.now[:alert] = @errors
      render :new
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to foods_path, notice: "Deleted Food: #{food.name}"
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @foods = Food.all # Replace this with the appropriate query to fetch the food records
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(params[:recipe_id]), notice: 'Recipe food was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_food.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Recipe_food is successfully Created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy

    redirect_to recipe_path(params[:recipe_id]), status: :see_other
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show public]
  def index
    @recipes = current_user.recipe
  end

  def show
    @recipe = Recipe.find(params[:id])
    return unless !user_signed_in? && !@recipe.public

    redirect_to new_user_session_path
  end

  def public
    @recipes = Recipe.includes(:user, :recipe_food).where(public: true).order(created_at: :desc)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: 'Recipe is successfully Created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      msg = 'Recipe is Private'
      msg = 'Recipe is Public' if @recipe.public
      redirect_to recipe_path(@recipe), notice: msg
    else
      redirect_to recipe_path(@recipe), alert: 'Someting is wrong'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path, status: :see_other
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def generate
    @recipes = current_user.recipe.includes(:food)
    @missing_foods = {}
    @total_value = 0

    @recipes.each do |recipe|
      recipe.recipe_food.each do |recipe_food|
        food = recipe_food.food
        total_quantity = recipe_food.quantity

        if @missing_foods[food].nil?
          @missing_foods[food] = total_quantity
        else
          @missing_foods[food] += total_quantity
        end
      end
    end

    @missing_foods.each do |food, quantity|
      food_quantity = food.quantity
      missing_quantity = quantity - food_quantity
      @missing_foods[food] = missing_quantity
      @total_value += missing_quantity * food.price
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_form.html.erb
<% if @errors.present? %>
  <div class = "errors_container">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@food do |form| %>
  <div class = "form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class = "form-group">
    <%= form.label :measurement %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div class = "form-group">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class = "form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class = "actions">
    <%=form.submit "Create Food"%>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class>
<h1 style='text-align: center'>Food List</h1>
<div style="display: flex; justify-content: flex-end; margin-bottom:20px">
  <%= link_to "Add Food", new_food_path, class: "btn btn-primary" %>
</div>
<table class="foods table table-bordered table-striped">
  <thead>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit price</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td>$<%= food.price %></td>
        <td><%= food.quantity %></td>
        <td><%= button_to "Remove", food_path(food), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/foods/new.html.erb
<h1>Add Food</h1>

<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="container-sm">
      <%= render 'shared/nav_bar'%>
    </header>
      <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p>
    <main class="container-sm">
    <%= yield %>
    </main>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<div class="card">
    <div class="card-header">
        <h1 class="card-title">Edit Ingredient.</h1>
    </div>
    <div class="card-body">
    <%= form_with model: @recipe_food, url: recipe_recipe_food_path, method: :put do |f| %>
        <%= f.hidden_field :id, value: @recipe_food.id %>
        <%= f.hidden_field :recipe_id, value: @recipe_food.recipe_id %>
        <div class="field-recipe">
          <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class: "form-control"} %>
        </div>
        <div class="field-recipe">
          <%= f.number_field :quantity, placeholder: 'Quantity', min: 0, required: true, class: "form-control" %>
        </div>
        <div class="actions-recipe">
          <%= f.submit "Add Ingredient", class: 'btn' %>
        </div>
      <% end %>
    </div>
</div>

app/views/recipe_foods/new.html.erb
<%= form_with model:([@recipe, @recipe_food]) do |form|%>
<h1 class="text-center mb-3">Add Food in Recipe</h1>

<div class="mb-3">
  <%= form.label :food_id, class: "form-label" %>
  <%= form.collection_select :food_id, current_user.food.all, :id, :name , {}, class: "form-select"%>
</div>

<div class="mb-3">
<%=form.label :quantity, class: "form-label"%>
<%=form.number_field :quantity, class: "form-control"%>
</div>

<%=form.submit "Create", class: "btn btn-primary"%>
<%end%>

app/views/recipes/index.html.erb
<div class="d-flex justify-content-end mb-3">
<%= button_to "Create Recipe", new_recipe_path, method: :get, class: "btn btn-primary" %>
</div>
<ul class="list-group">
<%@recipes.each do |recipe|%>
<li class="list-group-item">

<div class="card">
  <div class="row no-gutters">
    <div class="col-md-4">
      <div class="card-body">
        <h5 class="card-title">
          <%= link_to recipe do%>
          <%=recipe.name%>
          <%end%>
        </h5>
        <%= button_to "REMOVE", recipe_path(recipe), method: :delete, class: "btn btn-primary", id: "remove-button-#{recipe.id}"%>
      </div>
    </div>
    <div class="col-md-8">
      <div class="card-body text-right">
        <p class="card-text"><%=recipe.description%></p>
      </div>
    </div>
  </div>
</div>

</li>
<%end%>
<%%>
</ul>

app/views/recipes/new.html.erb
<%= form_with model:@recipe do |form|%>
<h1 class="text-center mb-3">Create Recipe</h1>
  <div class="mb-3">
<%=form.label :name, class: "form-label"%>
<%=form.text_field :name, class: "form-control"%>
</div>
  <div class="mb-3">
<%=form.label :preparation_time, class: "form-label"%>
<%=form.number_field :preparation_time, class: "form-control"%>
</div>
  <div class="mb-3">
<%=form.label :cooking_time, class: "form-label"%>
<%=form.number_field :cooking_time, class: "form-control"%>
</div>

  <div class="mb-3">
  <%= form.label :public, class: "form-check-label"%>
  <%= form.check_box :public, class: "form-check-input"%>
</div>

  <div class="mb-3">
<%=form.label :description, class: "form-label"%>
<%=form.text_area :description, class: "form-control"%>
</div>
<%=form.submit "Create", class: "btn btn-primary"%>
<%end%>

app/views/recipes/public.html.erb
<h1 style='text-align: center'>Public Recipes</h1>
<div class = "public_recipes" style='display: flex; justify-content: center; align-items: center; flex-direction: column'>
  <% @recipes.each do |recipe| %>
    <div class = "recipe_container" style='display: flex; margin: 25px 0; border: 1px solid #d0d1d1; padding: 10px;'>
      <div class = "recipe_creator" style='margin-right: 30px'>
        <h3><%= link_to recipe.name, recipe_path(id: recipe.id) %></h3>
        <p>By: <%= recipe.user.name %></p>
      </div>
      <div class = "recipe_details">
        <p>Total food items: <%= recipe.recipe_food.count %></p>
        <p>Total price: $<%=recipe.recipe_food.sum { |recipe_food| recipe_food.quantity * recipe_food.food.price }%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div>
<h1 class="text-center mb-3"><%=@recipe.name%></h1>
<div class="d-flex justify-content-between mb-3">
<div class="fs-4">Preparation time: <%=@recipe.preparation_time%> hours</div>
<% if user_signed_in? && current_user.id == @recipe.user_id %>
<%= render 'shared/toggle_btn', recipe: @recipe%>
<%end%>
</div>
<div class="fs-4">Cooking time: <%=@recipe.cooking_time%> hours</div>
<p class="text-break fs-4">Process: <%=@recipe.description%></p>
<div class="d-flex justify-content-between mb-3">
<% if user_signed_in? && current_user.id == @recipe.user_id %>
<%= button_to "Generate shopping list", generate_shopping_list_path, method: :get, class: "btn btn-primary" %>
<%= button_to "Add Ingredient", new_recipe_recipe_food_path(@recipe), method: :get, class: "btn btn-primary" %>
<%end%>
</div>
<%= render partial: 'shared/recipe_food_table', locals: { recipe_foods: @recipe.recipe_food, user_id: @recipe.user_id } %>
</div>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mt-4">
  <div class="container-fluid">
  <% if user_signed_in? %>
    <a class="navbar-brand" href="/"><h1><%=current_user.name%></h1></a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Food", foods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Recipe", recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Shopping list", generate_shopping_list_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-dark' %>
        </li>
      </ul>
    </div>
    <%else%>
    <a class="navbar-brand" href="/"><h1>Recipe App</h1></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= button_to 'Sign In', new_user_session_path, method: :get, class: 'btn btn-dark' %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign Up', new_user_registration_path, method: :get, class: 'btn btn-dark ms-3' %>
        </li>
      </ul>
      </div>
    <%end%>

  </div>
</nav>

app/views/shared/_recipe_food_table.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <% if user_signed_in? && current_user.id == user_id %>
        <th>Action</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= "#{recipe_food.quantity} #{recipe_food.food.measurement_unit}" %></td>
        <td><%= recipe_food.quantity * recipe_food.food.price %></td>
        <% if user_signed_in? && current_user.id == user_id %>
          <td>
            <div class="d-flex mb-3">
              <%= button_to "Modify", edit_recipe_recipe_food_path(recipe_food.recipe, recipe_food), method: :get, class: "btn btn-primary ms-3" %>
              <%= button_to "Remove", recipe_recipe_food_path(recipe_food.recipe, recipe_food), method: :delete, class: "btn btn-danger ms-3" %>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_toggle_btn.html.erb
<%= form_with(model: recipe, url: recipe_path(recipe), method: :patch, id: 'recipe-form') do |form| %>
  <div class="form-check form-switch">
    <%= form.check_box :public, class: 'form-check-input', id: 'toggle-btn', data: { public: recipe.public } %>
    <%= form.label :public, class: 'form-check-label' %>
  </div>
<% end %>
<%= javascript_include_tag 'toggle_btn' %>

app/views/shopping_lists/generate.html.erb
<div>
<h1 class="text-center mb-3">Shopping List</h1>
<div class="d-flex justify-content-between mb-3">
<span class="fs-4">Food item to buy: <%=@missing_foods.length%></span>
<span class="fs-4">Total: $<%=@total_value%></span>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
  <% @missing_foods.each do |food, quantity|%>
    <tr>
      <td><%=food.name%></td>
      <td><%="#{quantity} (#{food.measurement_unit})"%></td>
      <td>$<%=quantity * food.price%></td>
    </tr>
  <%end%>
  </tbody>
</table>
</div>